config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root to: redirect('/dashboard')
  get '/dashboard', to: 'pages#dashboard'

  resources :notebooks do
    get :new_folder
    post :create_folder
    patch :delete
    delete :hard_delete
    resources :notes do
      patch :delete
      delete :hard_delete
    end
  end
end

app/models/notebook.rb
# frozen_string_literal: true

class Notebook < ApplicationRecord
  include DecodableParamsConcern

  belongs_to :status
  belongs_to :owner, class_name: 'User'
  belongs_to :parent, class_name: 'Notebook', optional: true

  has_many :notes, dependent: :destroy
  has_many :notebooks, class_name: 'Notebook', foreign_key: 'parent_id'

  validates :name, presence: true, length: { maximum: 30 }

  scope :root, -> { where(parent_id: nil) }
  scope :active, -> { joins(:status).where.not(statuses: { name: Status::OPERATIONAL[:pending_for_delete] }) }

  def items
    [notes.active, notebooks.active].flat_map(&:itself)
      .sort_by { |item| [item.name ? 0 : 1, item.name || 0] }
  end

  def child_notebook?
    parent_id.present?
  end

  def outermost_parent
    current_notebook = self
    current_notebook = current_notebook.parent while current_notebook.parent.present?
    current_notebook
  end

  def all_notes
    subquery = <<-SQL.squish
      WITH RECURSIVE notebook_tree AS (
        SELECT id
        FROM notebooks
        WHERE id = :notebook_id
      UNION ALL
        SELECT n.id
        FROM notebooks n
        INNER JOIN notebook_tree nt ON nt.id = n.parent_id
      )
      SELECT id FROM notebook_tree
    SQL

    Note.where("notebook_id IN (#{subquery})", notebook_id: id)
  end
end

app/controllers/notebooks_controller.rb
# frozen_string_literal: true

class NotebooksController < ApplicationController
  include DecodableParamsController
  helper_method :new_folder?

  DEFAULT_PARENT_ATTRIBUTES = ['owner_id', 'status_id'].freeze

  def index
  end

  def new
    @notebook = Notebook.new
  end

  def new_folder
    parent_notebook = Notebook.find(params[:notebook_id])
    @notebook = parent_notebook.notebooks.new
  end

  def show
    @notebook = Notebook.find(params[:id])
  end

  def create
    @notebook = Notebook.new(notebook_params)
    @notebook.owner = current_user
    @notebook.status = Status.find_by(name: Status::PRIVACY[:private])
    if @notebook.save
      respond_to do |format|
        format.turbo_stream
      end
    else
    puts "Failed to save notebook: #{@notebook.errors.full_messages.join(", ")}"
      render :new, status: :unprocessable_entity
    end
  end

  def create_folder
    parent_notebook = Notebook.find(params[:notebook_id])
    default_parent_attributes = parent_notebook.attributes.slice(*DEFAULT_PARENT_ATTRIBUTES)
    @notebook = parent_notebook.notebooks.build(default_parent_attributes.merge(notebook_params))

    if @notebook.save
      respond_to do |format|
        format.turbo_stream
      end
    else
      render :new_folder, status: :unprocessable_entity
    end
  end

  def delete
    notebook = Notebook.find(params[:notebook_id])
    notebook.status = Status.find_by(name: Status::OPERATIONAL[:pending_for_delete])
    notebook.save
  end

  private

  def notebook_params
    params.require(:notebook).permit(
      :name,
    )
  end

  def new_folder?
    request.path.include?('new_folder')
  end
end

app/helpers/notebooks_helper.rb
# frozen_string_literal: true

module NotebooksHelper
  def status_icon(status_name)
    {
      'published' => 'globe',
      'private' => 'lock',
      'shared' => 'user-group',
    }[status_name]
  end

  def notebook_item(notebook)
    active_class = active_class(notebook_path(notebook))
    link_to notebook_path(notebook), class: "notebook #{active_class}" do
      concat content_tag(:span, '', class: 'active-indicator') if active_class
      concat fa_icon 'book'
      concat content_tag(:span, notebook.name)
    end
  end

  def dynamic_action(notebook)
    { action: notebook.parent.present? ? :create_folder : :create }
  end
end

app/views/notebooks/_content_menu.html.haml
= context_menu "content", data_options: { controller: 'url-helper'} do
  = context_menu_item notebook_notes_path(notebook), 'New note', 'pen-to-square', data: { item: :new_note, turbo_method: :post }
  = context_menu_item notebook_new_folder_path(notebook), 'New folder', 'folder-plus', data: { item: :new_folder, turbo_frame: :new_notebook }
  = context_menu_item '#', 'Rename', 'pen', data: { item: :rename }
  = context_menu_item notebook_delete_path(notebook), 'Move to Trash', 'trash-can', data: { item: :delete_folder, turbo_method: :patch }
  - if note.present?
    = context_menu_item notebook_note_delete_path(notebook.outermost_parent, note), 'Move to Trash', 'trash-can', data: { item: :delete_note, turbo_method: :patch, action: 'click->url-helper#addCurrentUrl' }

app/views/notebooks/_form.html.haml
- placeholder = @notebook.parent.present? ? 'Folder name' : 'Notebook name'
= form_with(model: @notebook, url: dynamic_action(@notebook), class: 'action-form') do |f|
  = f.label :name
  = f.text_field :name, placeholder: placeholder, autofocus: true, autocomplete: 'off'
  - if @notebook.errors[:name].any?
    %span.error
      = @notebook.errors.full_messages_for(:name).first

  = modal_actions do
    = action_button 'Cancel', '#', style: 'sub-action', data: { action: 'click->modal#toggle' }
    = f.submit 'Create', class: 'btn btn-normal'

app/views/notebooks/_notebook_content.html.haml
- notebook.items.each do |note|
  = note_item notebook, note

app/views/notebooks/_notebook_menu.html.haml
.context-menu.hide{data: { "context-menu-target": 'menu', "context-menu-id": 'notebook' }}

app/views/notebooks/_sidebar.html.haml
= action_button 'New notebook', new_notebook_path, style: 'normal', icon: 'plus', data: { turbo_frame: :new_notebook }
= turbo_frame_tag :new_notebook
%div{ data: { controller: 'context-menu' }}
  %span.sub-sidebar-section-title Notebooks
  #notebooks
    - notebooks.each do |notebook|
      = notebook_item notebook
  = render 'notebooks/notebook_menu'
- if @notebook
  %div{ data: { controller: 'context-menu' }}
    = render 'notebooks/content_menu', notebook: @notebook, note: nil
    .sub-sidebar-section-title
      %span Notebook Content
      = tooltip_wrapper('Add content', allow_actions: ['new_note', 'new_folder', 'delete_folder'])
    = render 'shared/local_search_bar', placeholder: 'Search notebook...'
  = turbo_frame_tag :notebook_content, data: { turbo_permanent: true }

app/views/notebooks/create.turbo_stream.haml
= turbo_stream.append 'notebooks' do
  = notebook_item @notebook
= turbo_stream.update :new_notebook, ''

app/views/notebooks/create_folder.turbo_stream.haml
= turbo_stream.update :notebook_content do
  = render 'notebook_content', notebook: @notebook.outermost_parent
= turbo_stream.update :new_notebook, ''

app/views/notebooks/new.html.haml
= turbo_frame_tag :new_notebook do
  = modal title: 'Create new notebook', description: 'Notebooks help to keep notes organized under a common topic', overlay: true do
    = render 'form', url: new_notebook_path
  :javascript
    $('.status-option').on('click', function() {
      $(this).find("input[type='radio']").prop('checked', true)
    })

app/views/notebooks/new_folder.html.haml
= turbo_frame_tag :new_notebook do
  = modal title: 'Create new folder', description: 'Folders help to keep notes organized under a common subtopic. Just like a notebook.', overlay: true do
    = render 'form'

app/views/notebooks/show.html.haml
= turbo_stream.update :notebook_content do
  = render 'notebook_content', notebook: @notebook