config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  root to: redirect('/dashboard')
  get '/dashboard', to: 'pages#dashboard'

  resources :notebooks do
    get :new_folder
    post :create_folder
    patch :delete
    delete :hard_delete
    resources :notes do
      patch :delete
      delete :hard_delete
    end
  end
end

app/views/layouts/_header.html.haml
.header
  .header-actions
    = render 'shared/logo'
    = render 'shared/search_bar'
  = avatar with_expander: true

app/views/layouts/_main_sidebar.html.haml
= main_sidebar do
  = main_sidebar_item(dashboard_path, 'Dashboard', 'house')
  = main_sidebar_item(notebooks_path, 'Notebooks', 'book')
  = main_sidebar_item('#', 'Published Notes', 'square-share-nodes')

app/views/layouts/_secondary_sidebar.html.haml
= sub_sidebar do
  = sub_sidebar_item("notebooks")
  = sub_sidebar_item("notes")

app/views/layouts/_sub_sidebar.html.haml
= sub_sidebar do
  = sub_sidebar_item("notebooks")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Inbox
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{content: "false", name: "turbo-prefetch"}/
    %meta{content: "no-preview", name: "turbo-cache-control"}/
    %meta{content: "morph", name: "turbo-refresh-method"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    = javascript_include_tag "jquery", "data-turbo-track": "reload"
    %script{crossorigin: "anonymous", src: "https://kit.fontawesome.com/9255a9b9ab.js"}
  %body{data: { controller: 'application' }}
    = render "layouts/header"
    .container
      = render 'shared/alert_modal'
      = render "layouts/main_sidebar"
      = render "layouts/secondary_sidebar"
      = turbo_frame_tag :page_content do
        = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Inbox
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_include_tag "application", "data-turbo-track": "reload", type: "module"
    %script{crossorigin: "anonymous", src: "https://kit.fontawesome.com/9255a9b9ab.js"}
  %body
    = yield